# Site settings
title: Human Can Code
email: your-email@domain.com
description: Just a simple site description here.
baseurl: "" # the subpath for your Jekyll, for example the"/subpath" bit in the url: http://yourdomain.com/subpath
url: "" # your site's url

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false  
  syntax_highlighter: rouge

# Excerpts
excerpt_separator: "<!-- more -->"

# Pretty URL
permalink: pretty

#highlighter
highlighter: rouge

# Assets 
#
# Enable the use of @imports in Jekyll:
sass:
 sass_dir: assets/scss
 style: :nested

authors:
  djerah_ahmed_rafik:
    name: Djerah Ahmed Rafik
    email: djerahahmedrafik@mail.com
    image: http://res.cloudinary.com/drvdrt7fn/image/upload/c_thumb,h_180,w_180/v1518603995/IMG_20171211_155033.jpg
